#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/ahmed/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/ahmed/Projects/Tibyan-Quran-App"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/ahmed/Projects/Tibyan-Quran-App/macos/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.4.0"
export "FLUTTER_BUILD_NUMBER=29"
export "DART_DEFINES=RkxVVFRFUl9CVUlMRF9OQU1FPTAuNC4w,RkxVVFRFUl9CVUlMRF9OVU1CRVI9Mjk=,RkxVVFRFUl9WRVJTSU9OPTMuNDcuNQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NmExOWNjYTU2NA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049YWY3ZTc5NmUxNg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy40"
export "DART_OBFUSCATION=false"
export "BUILD_NUMBER=29"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/ahmed/Projects/Tibyan-Quran-App/.dart_tool/package_config.json"
