"""Put the tajweed data in front of a qualified reader, as review drafts (ن15).

The tajweed colouring comes from cpfair/quran-tajweed (CC BY 4.0): rules
generated by decision trees, never checked by a person and unmaintained
since 2021. build_tajweed.py moves them onto the KFGQPC words and stores
them in content.db (`tajweed_letter`). This script copies those rows,
unchanged, into a review database: one entry per verse, listing every rule
on every letter of the verse, so a reader can see each verse coloured in
apps/review/ and approve it or note what is wrong.

Which verses (docs/MISSING_DATA.md, ن15): the whole of Juz' 'Amma, and a
fixed random sample of the rest (seeded, so the same verses come out on
every run).

Entry text, one line per rule on a letter (the review tool parses the part
in brackets to colour the letter; the rest is for the reader):
    ك3 ح2 «ٱللَّهِ» اللام الشمسية [lam_shamsiyyah 3:1:body]
word from 1 (۞ not counted), letter from 0 in brackets and from 1 before
them, part `body` (the letter) or `marks` (only its marks).

Nothing here is written by the script: the rules are the source's, the
words are the KFGQPC text, the rule names are the app's own legend.

Usage:
  python3 tools/import_tajweed_review.py              # data/review/tajweed_hafs.review.db
  python3 tools/import_tajweed_review.py --sample 300 --out X.db
"""
import argparse
import json
import random
import sqlite3
import sys
import unicodedata
from pathlib import Path

import review_db

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
CONTENT_DB = REPO / 'assets' / 'db' / 'content.db'
DEFAULT_OUT = REPO / 'data' / 'review' / 'tajweed_hafs.review.db'
SCRIPT = 'script:import_tajweed_review@1'
SEED = 1441
SAMPLE = 300
KIND = 'tajweed_verse'

# The app's legend (lib/l10n/app_ar.arb, tajweed*), in build_tajweed.RULES order.
RULE_NAMES = {
    'hamzat_wasl': 'همزة الوصل',
    'lam_shamsiyyah': 'اللام الشمسية',
    'silent': 'الحروف التي لا تُنطق',
    'madd_2': 'المد الطبيعي (حركتان)',
    'madd_246': 'المد العارض واللين (2 أو 4 أو 6 حركات)',
    'madd_muttasil': 'المد المتصل (4 أو 5 حركات)',
    'madd_munfasil': 'المد المنفصل (4 أو 5 حركات)',
    'madd_6': 'المد اللازم (6 حركات)',
    'ghunnah': 'الغنة',
    'ikhfa': 'الإخفاء',
    'ikhfa_shafawi': 'الإخفاء الشفوي',
    'iqlab': 'الإقلاب',
    'idghaam_ghunnah': 'الإدغام بغنة',
    'idghaam_no_ghunnah': 'الإدغام بلا غنة',
    'idghaam_shafawi': 'الإدغام الشفوي',
    'idghaam_mutajanisayn': 'إدغام المتجانسين',
    'idghaam_mutaqaribayn': 'إدغام المتقاربين',
    'qalqalah': 'القلقلة',
}
PART_NAMES = {'body': '', 'marks': ' (الحركات)'}
HIZB = '۞'


def words_of(display_text):
    """The verse's words as tajweed_letter counts them: the KFGQPC tokens
    without ۞ and without the verse-number glyph at the end."""
    tokens = display_text.split()[:-1]
    return [t for t in tokens if t != HIZB]


def letters(word):
    """Character spans of a word's letters (build_tajweed.letters)."""
    out = []
    for i, ch in enumerate(word):
        if unicodedata.category(ch).startswith('L') or not out:
            out.append([i, i + 1])
        else:
            out[-1][1] = i + 1
    return out


def entry_text(words, rows):
    lines = []
    for word, letter, part, rule in rows:
        w = words[word - 1]
        lines.append(f'ك{word} ح{letter + 1} «{w}» {RULE_NAMES[rule]}{PART_NAMES[part]} '
                     f'[{rule} {word}:{letter}:{part}]')
    return '\n'.join(lines)


def choose(verses, sample, seed=SEED):
    """Juz' 30 whole, then `sample` verses of the rest, in mushaf order."""
    juz30 = [k for k, v in verses.items() if v['juz'] == 30]
    rest = sorted(k for k, v in verses.items() if v['juz'] != 30)
    picked = random.Random(seed).sample(rest, min(sample, len(rest)))
    return sorted(juz30) + sorted(picked), len(juz30)


def build(out, content_db, sample):
    src = sqlite3.connect(f'file:{content_db}?mode=ro', uri=True)
    verses = {(s, a): {'display': d, 'juz': j, 'page': p} for s, a, d, j, p in src.execute(
        'SELECT surah, number, display_text, juz, page FROM ayah')}
    names = dict(src.execute('SELECT id, name_ar FROM surah'))
    rows = {}
    for s, a, w, l, part, rule in src.execute(
            "SELECT surah, ayah, word, letter, part, rule FROM tajweed_letter "
            "WHERE riwaya = 'hafs' ORDER BY surah, ayah, word, letter, part, rule"):
        rows.setdefault((s, a), []).append((w, l, part, rule))
    source = src.execute(
        "SELECT title, publisher, version, license, url FROM source WHERE id = 18").fetchone()
    src.close()

    keys, in_juz30 = choose(verses, sample)
    db = review_db.create(out, content_db)
    row = {
        'key': 'tajweed_cpfair_hafs',
        'kind': 'tajweed',
        'title': 'أحكام التجويد لرواية حفص (بيانات التلوين في التطبيق)',
        'author': 'cpfair/quran-tajweed (مولدة آليا)',
        'edition': source[2] if source else None,
        'publisher': source[1] if source else None,
        'tahqiq': None,
        'licence': source[3] if source else 'CC BY 4.0',
        'digitised_by': 'tools/build_tajweed.py (نقلها إلى كلمات نص المجمع)',
        'url': source[4] if source else 'https://github.com/cpfair/quran-tajweed',
        'file': 'assets/db/content.db (tajweed_letter)',
        'sha256': review_db.sha256_file(content_db),
        'retrieved_at': review_db.now()[:10],
        'notes': f"Juz' 30 whole ({in_juz30} verses) and {len(keys) - in_juz30} verses of the "
                 f'rest drawn with seed {SEED}. Approve a verse when every coloured letter '
                 'carries the right rule and no rule is missing; otherwise write what is wrong '
                 'in the note.',
    }
    source_id = review_db.add_source(db, row)
    stats = {'entries': 0, 'juz30': in_juz30, 'sample': len(keys) - in_juz30, 'rules': 0,
             'verses_without_rules': 0, 'letters_out_of_range': 0}
    for seq, (s, a) in enumerate(keys, 1):
        v = verses[(s, a)]
        words = words_of(v['display'])
        rs = rows.get((s, a), [])
        notes = []
        for w, l, _, _ in rs:
            if w > len(words) or l >= len(letters(words[w - 1])):
                notes.append(f'letter {w}:{l} is not in the KFGQPC verse')
        stats['letters_out_of_range'] += len(notes)
        if not rs:
            stats['verses_without_rules'] += 1
            notes.append('no rule on this verse in the data')
        entry = {'seq': seq, 'kind': KIND, 'section': f'{names[s]} {a}', 'volume': None,
                 'page': v['page'], 'page_end': None, 'text': entry_text(words, rs),
                 'notes': notes}
        link = {'surah': s, 'ayah_from': a, 'ayah_to': a, 'basis': 'marker', 'confidence': 1.0}
        review_db.add_draft(db, source_id, row['key'], entry, [link], SCRIPT)
        stats['entries'] += 1
        stats['rules'] += len(rs)
    db.execute("INSERT INTO meta VALUES ('import_stats', ?)", (json.dumps(stats, sort_keys=True),))
    db.commit()
    db.close()
    return stats


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--out', type=Path, default=DEFAULT_OUT)
    ap.add_argument('--content-db', type=Path, default=CONTENT_DB)
    ap.add_argument('--sample', type=int, default=SAMPLE)
    args = ap.parse_args(argv)
    print(json.dumps(build(args.out, args.content_db, args.sample), sort_keys=True, indent=1))
    return 0


if __name__ == '__main__':
    sys.exit(main())
